# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  赵梓杉的博客
subtitle: 知识的追随者！
name: 赵梓杉 
email: 
description: 本站是zhao zishan的分享博客-Python学起来！
keywords: Python, 数据分析, 数据科学
encoding: "utf-8"
favicon: favicon.ico 

repository: PythonDS/PythonDS.github.io
github_url: https://github.com/PythonDS
url: http://www.zhaozishan.com
enforce_ssl: zhaozishan.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
  -
  -
    href: /about.html
    label: 关于
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home




# labels. my blog key words
labels:

  -
    href: /gitchat.html
    label: Chat
    target: _blank


# selected articles
classes:

  -
    href: /cartoon.html
    name: python达人-小溪
    describe: 看似内心沉稳 ，实则放荡不羁。




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhaozishan
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhaozishan
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhaozishan
    repo: blog-comments
    clientID: 61bfc53d957e74e78f8f
    clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
theme: jekyll-theme-cayman
